IBM/networking-go-sdk

directlinkapisv1/direct_link_apis_v1_integration_test.go, transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go
Added additional API response validation for both DirectLink and Transit APIs
=> Enhanced integration tests

.travis.yml
=> feat(build): Initial deployment

.travis.yml, Makefile
=> feat(build): Added the makefile to run builds and test cases

.travis.yml
=> feat(build): Enable deployment from Travis CI

README.md
updated the semantic tags in readme
=> chore(readme): updated the semantic tags in readme

README.md
=> chore(doc): update issue link in readme

.travis.yml, directlinkv1/direct_link_v1_integration_test.go, transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go
=> chore: disable transit integration tests

dnsrecordsv1/dns_records_v1.go, dnsrecordsv1/dns_records_v1_integration_test.go, dnsrecordsv1/dns_records_v1_test.go
=> DNS Record TTL update

directlinkv1/direct_link_v1_integration_test.go
=> fix: fixed the integration tests for direct link

cachingapiv1/caching_api_v1_integration_test.go, custompagesv1/custom_pages_v1_integration_test.go, firewallapiv1/firewall_api_v1_integration_test.go, globalloadbalancermonitorv1/global_load_balancer_monitor_v1.go, globalloadbalancermonitorv1/global_load_balancer_monitor_v1_integration_test.go, globalloadbalancermonitorv1/global_load_balancer_monitor_v1_test.go, globalloadbalancerv1/global_load_balancer_v1_integration_test.go, zonessettingsv1/zones_settings_v1_integration_test.go
=> feat(glb monitor): added header field in output

README.md
=> chore: updated readme with provider sdk content

directlinkv1/direct_link_v1_integration_test.go
=> test: fixed the locations test case

globalloadbalancerpoolsv0/global_load_balancer_pools_v0.go, globalloadbalancerpoolsv0/global_load_balancer_pools_v0_integration_test.go, globalloadbalancerpoolsv0/global_load_balancer_pools_v0_test.go
=> CIS: glb pool regions and origins result update

globalloadbalancersv1/global_load_balancers_v1.go, globalloadbalancersv1/global_load_balancers_v1_integration_test.go, globalloadbalancersv1/global_load_balancers_v1_suite_test.go, globalloadbalancersv1/global_load_balancers_v1_test.go
PDNS GLB Monitor,Pool and load balancer file changes
=> PDNS GLB Monitor,Pool and load balancer file changes

directlinkv1/direct_link_v1.go, directlinkv1/direct_link_v1_integration_test.go, directlinkv1/direct_link_v1_suite_test.go, directlinkv1/direct_link_v1_test.go
This PR adds the support for macsec enabled gateways in direct link
=> feat: added the support for macsec enabled gateways in direct link

directlinkv1/direct_link_v1.go, directlinkv1/direct_link_v1_integration_test.go, directlinkv1/direct_link_v1_test.go
updated the macsec fields as per latest api spec
=> fix: updated the macsec fields as per latest api spec

CHANGELOG.md, DEPRECATION-NOTICE.md, README.md, dnsgloballoadbalancersv1/dns_global_load_balancers_v1.go, dnsgloballoadbalancersv1/dns_global_load_balancers_v1_integration_test.go, dnsgloballoadbalancersv1/dns_global_load_balancers_v1_suite_test.go, dnsgloballoadbalancersv1/dns_global_load_balancers_v1_test.go, dnspermittednetworksv1/dns_permitted_networks_v1.go, dnspermittednetworksv1/dns_permitted_networks_v1_integration_test.go, dnspermittednetworksv1/dns_permitted_networks_v1_suite_test.go, dnspermittednetworksv1/dns_permitted_networks_v1_test.go, dnsresourcerecordsv1/dns_resource_records_v1.go, dnsresourcerecordsv1/dns_resource_records_v1_integration_test.go, dnsresourcerecordsv1/dns_resource_records_v1_suite_test.go, dnsresourcerecordsv1/dns_resource_records_v1_test.go, package-lock.json
1. Added renamed-sdk for PDNS services
2. Added deprecation notice md file
3. Added deprecation comment on old sdks
4. Edited README.md file for the deprecation changes.
=> PDNS: Added renamed-sdk and deprecation notice

directlinkv1/direct_link_v1.go, directlinkv1/direct_link_v1_integration_test.go, directlinkv1/direct_link_v1_test.go
made bgp_base_cidr optional and added customer and carrier name in get gateways
=> fix: made bgp_base_cidr optional and added customer and carrier name in get gateways

cachingapiv1/caching_api_v1.go, cachingapiv1/caching_api_v1_integration_test.go, cachingapiv1/caching_api_v1_suite_test.go, cachingapiv1/caching_api_v1_test.go, sslcertificateapiv1/ssl_certificate_api_v1_integration_test.go
=> Adding Alwasy Online feature to Caching API

.secrets.baseline, filtersv1/filters_v1.go, filtersv1/filters_v1_integration_test.go, filtersv1/filters_v1_suite_test.go, filtersv1/filters_v1_test.go, firewallrulesv1/firewall_rules_v1.go, firewallrulesv1/firewall_rules_v1_integration_test.go, firewallrulesv1/firewall_rules_v1_suite_test.go, firewallrulesv1/firewall_rules_v1_test.go, sslcertificateapiv1/ssl_certificate_api_v1_integration_test.go
=> CIS SDK for filters and Firewall rules

zonessettingsv1/zones_settings_v1.go, zonessettingsv1/zones_settings_v1_integration_test.go, zonessettingsv1/zones_settings_v1_test.go
=> added http3 settings

.secrets.baseline, dnsrecordbulkv1/dns_record_bulk_v1_integration_test.go, dnsrecordsv1/dns_records_v1_integration_test.go, filtersv1/filters_v1.go, filtersv1/filters_v1_integration_test.go, filtersv1/filters_v1_suite_test.go, filtersv1/filters_v1_test.go, firewallrulesv1/firewall_rules_v1.go, firewallrulesv1/firewall_rules_v1_integration_test.go, firewallrulesv1/firewall_rules_v1_suite_test.go, firewallrulesv1/firewall_rules_v1_test.go
=> feat(Filters & Firewall_Rules): Response changed from io.Read to Struct

.secrets.baseline, dnssvcsv1/dns_svcs_v1_integration_test.go, transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go
=> feat(DNS Records): Added sdk for Import/Export dns records

.github/workflows/codeql-analysis.yml, transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go
Set CodeQL scanning to run weekly in addition to on code checkins
=> chore: weekly static analysis cron job

.travis.yml, directlinkproviderv2/direct_link_provider_v2.go, directlinkproviderv2/direct_link_provider_v2_integration_test.go, directlinkproviderv2/direct_link_provider_v2_suite_test.go, directlinkproviderv2/direct_link_provider_v2_test.go, directlinkv1/direct_link_v1.go, directlinkv1/direct_link_v1_integration_test.go, directlinkv1/direct_link_v1_test.go, dnssvcsv1/dns_svcs_v1_integration_test.go, go.sum
Implement the changes to update the BGP parameters - Remote and Local IP, ASN
Implement the changes to enable/update the BFD config
=> feat(DirectLink): add the changes to update the BGP parameters and enable BFD config on directlink gateways

directlinkproviderv2/direct_link_provider_v2_integration_test.go, directlinkv1/direct_link_v1_integration_test.go
=> chore: updated the core SDK to v5 for DirectLink Integration test cases

CHANGELOG.md, package-lock.json
* Added Gateway Route Reports Integration tests for GO-SDK. ([96b5ef1](https://github.com/IBM/networking-go-sdk/commit/96b5ef11a711f7fd6f0990bb43b6b446c5a1585c))
* Added Gateway Route Reports Integration tests for GO-SDK. ([162a024](https://github.com/IBM/networking-go-sdk/commit/162a02483988ce7ea60495e70a0897698218e02e))
* Added Gateway Route Reports Integration tests for GO-SDK. ([#67](https://github.com/IBM/networking-go-sdk/issues/67)) ([aa7b1b0](https://github.com/IBM/networking-go-sdk/commit/aa7b1b0915e95bc1f3508c94d6cd7bbef975d2b4))
=> chore(release): 0.24.0 release notes [skip ci]

alertsv1/alerts_v1_integration_test.go
=> feat(Alert-policies): added alter-policies

.secrets.baseline
=> chore: remove secrets

logpushjobsapiv1/logpush_jobs_api_v1_integration_test.go
=> chore(LogDNA): change integration file

.gitignore, alertsv1/alerts_v1_integration_test.go, cachingapiv1/caching_api_v1_integration_test.go, cisipapiv1/cis_ip_api_v1_integration_test.go, dnsrecordsv1/dns_records_v1_integration_test.go, edgefunctionsapiv1/edge_functions_api_v1_integration_test.go, filtersv1/filters_v1_integration_test.go, firewallapiv1/firewall_api_v1_integration_test.go, globalloadbalancereventsv1/global_load_balancer_events_v1_integration_test.go, globalloadbalancermonitorv1/global_load_balancer_monitor_v1_integration_test.go, globalloadbalancerpoolsv0/global_load_balancer_pools_v0_integration_test.go, globalloadbalancerv1/global_load_balancer_v1_integration_test.go, logpushjobsapiv1/logpush_jobs_api_v1_integration_test.go, routingv1/routing_v1__integration_test.go, securityeventsapiv1/security_events_api_v1_integration_test.go, transitgatewayapisv1/transit_gateway_apis_v1.go, transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go, transitgatewayapisv1/transit_gateway_apis_v1_suite_test.go, transitgatewayapisv1/transit_gateway_apis_v1_test.go, useragentblockingrulesv1/user_agent_blocking_rules_v1_integration_test.go, wafrulegroupsapiv1/waf_rule_groups_api_v1_integration_test.go, wafrulepackagesapiv1/waf_rule_packages_api_v1_integration_test.go, wafrulesapiv1/waf_rules_api_v1_integration_test.go, webhooksv1/webhooks_v1_integration_test.go, zonefirewallaccessrulesv1/zone_firewall_access_rules_v1_integration_test.go, zonelockdownv1/zone_lockdown_v1_integration_test.go, zoneratelimitsv1/zone_rate_limits_v1_integration_test.go, zonessettingsv1/zones_settings_v1_integration_test.go
Transit service update to include the new Prefix Filter APIs.
This includes unit and integration tests as well as related help documentation
**Fixes:** new feature
Please make sure that your PR fulfills the following requirements:  
Current Transit Gateway Connection APIs do not support new prefix filter feature.
Prefix filters are now supported by Transit Gateway Connection APIs
=> Update Transit service to include new Prefix Filter APIs.

transitgatewayapisv1/transit_gateway_apis_v1_test.go
=> feat: create new release

dnssvcsv1/dns_svcs_v1_integration_test.go
All `dnssvcsv1` integration tests were being skipped. With this PR, tests will now be run. Currently, only some tests are being skipped. Better test setup steps are needed.
=> fix(pdns cross acct): do not skip all tests

zonesv1/zones_v1.go, zonesv1/zones_v1_integration_test.go, zonesv1/zones_v1_suite_test.go, zonesv1/zones_v1_test.go
SDK Support for CNAME Setup - GO SDK
- Added partial zone setup
Please make sure that your PR fulfills the following requirements:  
We don't have option to set the zone type.
We can define zone type - full or partial
=> feat(zones): added partial zone setup

firewallrulesv1/firewall_rules_v1.go, firewallrulesv1/firewall_rules_v1_integration_test.go, firewallrulesv1/firewall_rules_v1_suite_test.go, firewallrulesv1/firewall_rules_v1_test.go, go.mod, go.sum
Added the following keys in the Firewall Rules arguments -
- priority
- paused
Original Issue : https://github.ibm.com/NetworkTribe/CIS_Support/issues/2515
=> feat: allow users to set priority for firewall_rules

cachingapiv1/caching_api_v1_integration_test.go
Skipped `cachingapiv1 purge all`.
=> CIS : Skipping Caching Purge All API

transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go, zonesv1/zones_v1_integration_test.go
=> skipping transitgatewayv1 tests

transitgatewayapisv1/transit_gateway_apis_v1_integration_test.go
=> removed unused code

dnssvcsv1/dns_svcs_v1_integration_test.go, filtersv1/filters_v1_integration_test.go, firewallrulesv1/firewall_rules_v1_integration_test.go, zoneratelimitsv1/zone_rate_limits_v1_integration_test.go
Fixing test cases for release.
=> fix test cases

dnssvcsv1/dns_svcs_v1_integration_test.go, dnssvcsv1/dns_svcs_v1_suite_test.go
Skipping DNS SVCS test cases, as a complete cleanup is already in progress.
=> skipping dns svcs test cases

dnssvcsv1/dns_svcs_v1_suite_test.go
=> added comment

.travis.yml
Update node version to 18 for Travis build
=> chore: update node version to 18

.travis.yml
Updated Travis build dist to Focal beta, to resolve build errors.
=> chore: updated to focal beta

botmanagementv1/bot_management_v1.go, botmanagementv1/bot_management_v1_integration_test.go, botmanagementv1/bot_management_v1_suite_test.go, botmanagementv1/bot_management_v1_test.go
=> feat: bot management

dnssvcsv1/dns_svcs_v1_integration_test.go
Please make sure that your PR fulfills the following requirements:  
Actual PR: https://github.com/IBM/networking-go-sdk/pull/134
=> feat: pDNS pagination feature

botanalyticsv1/bot_analytics_v1_integration_test.go
Added this PR for automated release cycle to trigger.
=> feat: Bot Analytics

botanalyticsv1/bot_analytics_v1.go, botanalyticsv1/bot_analytics_v1_integration_test.go
Parameter encoding was failing for specified date format. Fixed it now.
=> fix: parameter encoding fixed

directlinkv1/direct_link_v1.go, directlinkv1/direct_link_v1_suite_test.go, directlinkv1/direct_link_v1_test.go
Update to include new fields in DL Route Report
=> fix: update DL Route Report

README.md
**Fixes:** minor text update in order to re-trigger the travis jobs
=> chore: minor text changes

README.md
=> chore: minor text changes to re-trigger the build

.secrets.baseline
This PR is to suppress false positive found during detect secrets audit. 
**Fixes:** 
This PR is to suppress false positive found during detect secrets audit (false positives for dnssvc).
Please make sure that your PR fulfills the following requirements:  
This PR is to suppress false positive found during detect secrets audit.
=> feat: updating .secrets.baseline to suppress false positives for dnssvc

transitgatewayapisv1/transit_gateway_apis_v1.go, transitgatewayapisv1/transit_gateway_apis_v1_suite_test.go, transitgatewayapisv1/transit_gateway_apis_v1_test.go
A new ASN numbers were introduced, hence the new files required to be generated. 
**Fixes:** there was no issue to fix. 
=> feat: Updating the list of reserved ASN numbers

directlink.env.properties, directlinkproviderv2/direct_link_provider_v2.go, directlinkproviderv2/direct_link_provider_v2_integration_test.go, directlinkproviderv2/direct_link_provider_v2_suite_test.go, directlinkproviderv2/direct_link_provider_v2_test.go
=> Provider changes for VLAN

.travis.yml
Node version update to run semantic-release
=> fix: updated node version to run semantic-release

dnssvcsv1/dns_svcs_v1_integration_test.go, dnssvcsv1/dns_svcs_v1_test.go
Skipping failed test cases to allow successful build
=> Skipping failed test cases

rulesetsv1/rulesets_v1_integration_test.go
dependency: none 
Signed-off-by: arpit-srivastava-ibm <arpit.srivastava2@ibm.com>
=> feat(CIS) : WAF 2.0 Managed Rulesets

rulesetsv1/rulesets_v1_integration_test.go
* feat: release managed rulesets
Empty commit to trigger a release.
=> feat: release managed rulesets

.travis.yml
=> fix: update versions

.travis.yml
=> fix: yaml update

.travis.yml
**Fixes:** https://app.travis-ci.com/github/IBM/networking-go-sdk/jobs/623124862
```
nvm install 20
npm install -g npm@6.x
npm install @semantic-release/changelog
npm install @semantic-release/exec
npm install @semantic-release/git
npm install @semantic-release/github
pip install --user bump2version
DEPRECATION WARNING! We are moving to dpl v.2. If you want to preserve the current behavior and still use dpl v.1, add the dpl_version key with the desired version of the dpl gem (the last stable is 1.10.16) to your .travis.yml.
Installing deploy dependencies
Preparing deploy
Deploying application
failed to deploy
```
=> fix: fixing deployment issue

README.md
=> fix: reverting previous dependency update chnages

.travis.yml, common/version.go
=> fix: reverting previous dependency update changes

zonessettingsv1/zones_settings_v1.go, zonessettingsv1/zones_settings_v1_integration_test.go, zonessettingsv1/zones_settings_v1_suite_test.go, zonessettingsv1/zones_settings_v1_test.go
=> feat(CIS): origin post quantum encryption and max HTTP version

zonessettingsv1/zones_settings_v1.go, zonessettingsv1/zones_settings_v1_integration_test.go, zonessettingsv1/zones_settings_v1_suite_test.go, zonessettingsv1/zones_settings_v1_test.go
=> fix(CIS): proxy read timeout response

.bumpversion.cfg, CHANGELOG.md, README.md, common/version.go
=> fix(version): upgrade to 0.51.3

.bumpversion.cfg, CHANGELOG.md, README.md, common/version.go
=> fix(version): upgrade to 0.51.4

zonessettingsv1/zones_settings_v1.go, zonessettingsv1/zones_settings_v1_test.go
=> fix(CIS): update proxy read timeout response

rulesetsv1/rulesets_v1.go, rulesetsv1/rulesets_v1_integration_test.go, rulesetsv1/rulesets_v1_test.go
=> fix(cis): update skip action for rule for waf ruleset
